-- MySQL Script generated by MySQL Workbench
-- Thu Jul  3 23:48:37 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema varejopro
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema varejopro
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `varejopro` DEFAULT CHARACTER SET utf8 ;
USE `varejopro` ;

-- -----------------------------------------------------
-- Table `varejopro`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `varejopro`.`categorias` (
  `idcategorias` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcategorias`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `varejopro`.`fornecedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `varejopro`.`fornecedores` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(150) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `created_at` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `varejopro`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `varejopro`.`produtos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `preco_compra` DECIMAL(10,2) NOT NULL,
  `preco_venda` DECIMAL(10,2) NOT NULL,
  `qtde` INT NOT NULL,
  `marca` VARCHAR(45) NOT NULL,
  `validade` DATE NOT NULL,
  `created_at` DATE NOT NULL,
  `categorias_id` INT NOT NULL,
  `fornecedores_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_produtos_categorias_idx` (`categorias_id` ASC) VISIBLE,
  INDEX `fk_produtos_fornecedores1_idx` (`fornecedores_id` ASC) VISIBLE,
  CONSTRAINT `fk_produtos_categorias`
    FOREIGN KEY (`categorias_id`)
    REFERENCES `varejopro`.`categorias` (`idcategorias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produtos_fornecedores1`
    FOREIGN KEY (`fornecedores_id`)
    REFERENCES `varejopro`.`fornecedores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `varejopro`.`lista_vendas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `varejopro`.`lista_vendas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `produtos_id` INT NOT NULL,
  `qtde_item` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_lista_vendas_produtos1_idx` (`produtos_id` ASC) VISIBLE,
  CONSTRAINT `fk_lista_vendas_produtos1`
    FOREIGN KEY (`produtos_id`)
    REFERENCES `varejopro`.`produtos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `varejopro`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `varejopro`.`clientes` (
  `idclientes` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(150) NOT NULL,
  `created_at` DATE NOT NULL,
  PRIMARY KEY (`idclientes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `varejopro`.`vendas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `varejopro`.`vendas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `total_itens` INT NOT NULL,
  `lista_vendas_id` INT NOT NULL,
  `clientes_idclientes` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_vendas_lista_vendas1_idx` (`lista_vendas_id` ASC) VISIBLE,
  INDEX `fk_vendas_clientes1_idx` (`clientes_idclientes` ASC) VISIBLE,
  CONSTRAINT `fk_vendas_lista_vendas1`
    FOREIGN KEY (`lista_vendas_id`)
    REFERENCES `varejopro`.`lista_vendas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vendas_clientes1`
    FOREIGN KEY (`clientes_idclientes`)
    REFERENCES `varejopro`.`clientes` (`idclientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `varejopro`.`contas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `varejopro`.`contas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  `vencimento` DATE NOT NULL,
  `descricao` VARCHAR(250) NOT NULL,
  `status` ENUM("pago", "pendente") NOT NULL,
  `tipo` ENUM("pagar", "receber") NOT NULL,
  `parcelas` INT NOT NULL,
  `parcelas_rest` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `varejopro`.`lista_compras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `varejopro`.`lista_compras` (
  `id` INT NOT NULL,
  `produtos_id` INT NOT NULL,
  `qtde_item` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_lista_compras_produtos1_idx` (`produtos_id` ASC) VISIBLE,
  CONSTRAINT `fk_lista_compras_produtos1`
    FOREIGN KEY (`produtos_id`)
    REFERENCES `varejopro`.`produtos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `varejopro`.`compras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `varejopro`.`compras` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `total_itens` INT NOT NULL,
  `fornecedores_id` INT NOT NULL,
  `lista_compras_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_compras_fornecedores1_idx` (`fornecedores_id` ASC) VISIBLE,
  INDEX `fk_compras_lista_compras1_idx` (`lista_compras_id` ASC) VISIBLE,
  CONSTRAINT `fk_compras_fornecedores1`
    FOREIGN KEY (`fornecedores_id`)
    REFERENCES `varejopro`.`fornecedores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_compras_lista_compras1`
    FOREIGN KEY (`lista_compras_id`)
    REFERENCES `varejopro`.`lista_compras` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
